services:
  rsc-web:
    image: ghcr.io/musawenkos/rsc-web:latest
    build:
      context: .
      dockerfile: src/RoadSignCapture.Web/Dockerfile
    ports:
      - "5050:5050"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5050
      - AzureAd__ClientId=${AZ_CLIENTID}
      - AzureAd__ClientSecret=${AZ_CLIENT_SECRET}
      - AzureAd__Domain=${AZ_DOMAIN}
      - AzureAd__TenantId=${AZ_TENANTID}
      - AzureAd__CallbackPath=${AZ_CALLBACK_PATH}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - AzureAd__Instance=${AZ_INSTANCE}
      - MicrosoftGraph__BaseUrl=${MG_BASE_URL}
      - MicrosoftGraph__Scopes=${SCOPES}
      - API_BASE_URL=http://rsc-api:5040
      - Redis__Host=${REDIS_HOST}
      - Redis__Port=${REDIS_PORT}
    depends_on:
      - rsc-db
      - rsc-redis
    networks:
      - rsc-network

  rsc-api:
    image: ghcr.io/musawenkosi/rsc-api:latest
    build:
      context: .
      dockerfile: src/RoadSignCapture.API/Dockerfile
    ports:
      - "5040:5040"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    - ASPNETCORE_URLS=http://+:5040
    - Redis__Host=${REDIS_HOST}
    - Redis__Port=${REDIS_PORT}
    depends_on:
    - rsc-db
    - rsc-redis
    networks:
    - rsc-network

  rsc-db:
    container_name: rsc-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${DB_SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - rsc-network

  rsc-redis:
    image: redis:7.2
    container_name: rsc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - rsc-network


  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.2.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - rsc-network

  kib01:
    image: docker.elastic.co/kibana/kibana:9.2.0
    container_name: kib01
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - "5601:5601"
    depends_on:
      - es01
    networks:
      - rsc-network

volumes:
  sqlserverdata:
  redis_data:
  esdata01:
    driver: local

networks:
  rsc-network:
    driver: bridge
